name: "Feature Request"
description: Submit a proposal for a new OpenAdapt feature
labels: enhancement
body:
  - type: textarea
    id: feature-request
    validations:
      required: true
    attributes:
      label: Feature request
      description: A clear and concise description of the feature proposal. Please provide links to any relevant resources.

  - type: textarea
    id: motivation
    validations:
      required: false
    attributes:
      label: Motivation
      description: Please outline the purpose for the proposal (e.g., is it related to a problem?). Add any relevant links (e.g. GitHub issues).
      placeholder: I'm always frustrated when [...] so this feature would [...].
